{
 "title": "main",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Requests per Second",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (method, path, status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{method}} {{path}} ({{status}})"
    }
   ]
  },
  {
   "title": "notes created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "notes_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "notes created errors rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "notes_created_errors", "legendFormat": "__auto" }
   ]
  }
 ]
}