// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Mafit1/notes-app/internal/metrics (interfaces: NotesMetrics)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNotesMetrics is a mock of NotesMetrics interface.
type MockNotesMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockNotesMetricsMockRecorder
}

// MockNotesMetricsMockRecorder is the mock recorder for MockNotesMetrics.
type MockNotesMetricsMockRecorder struct {
	mock *MockNotesMetrics
}

// NewMockNotesMetrics creates a new mock instance.
func NewMockNotesMetrics(ctrl *gomock.Controller) *MockNotesMetrics {
	mock := &MockNotesMetrics{ctrl: ctrl}
	mock.recorder = &MockNotesMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotesMetrics) EXPECT() *MockNotesMetricsMockRecorder {
	return m.recorder
}

// IncCreated mocks base method.
func (m *MockNotesMetrics) IncCreated() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCreated")
}

// IncCreated indicates an expected call of IncCreated.
func (mr *MockNotesMetricsMockRecorder) IncCreated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCreated", reflect.TypeOf((*MockNotesMetrics)(nil).IncCreated))
}

// IncCreatedError mocks base method.
func (m *MockNotesMetrics) IncCreatedError() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncCreatedError")
}

// IncCreatedError indicates an expected call of IncCreatedError.
func (mr *MockNotesMetricsMockRecorder) IncCreatedError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncCreatedError", reflect.TypeOf((*MockNotesMetrics)(nil).IncCreatedError))
}
